# Generated by Django 4.2.5 on 2023-11-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_branch',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='car_type',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_passenger',
            field=models.BooleanField(default=True),
        ),
    ]
