# Generated by Django 4.2.5 on 2023-11-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_color',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='car_id',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
