# Generated by Django 4.2.5 on 2023-11-13 03:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='person',
        ),
        migrations.AddField(
            model_name='travels',
            name='actual_passangers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travels',
            name='conductor',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travels',
            name='max_passangers',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.travels')),
            ],
        ),
        migrations.AddField(
            model_name='travels',
            name='passangers',
            field=models.ManyToManyField(through='home.passanger', to='login.user'),
        ),
    ]
