# Generated by Django 4.2.5 on 2023-11-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travels2',
        ),
        migrations.RenameField(
            model_name='travels',
            old_name='person',
            new_name='driver',
        ),
    ]
